version: "3.9"
services:
  redis:
    image: redis:7.0
    container_name: redis-server
    restart: unless-stopped
    ports:
      - 6379:6379/tcp
    environment:
      - TX=Asia/Shanghai
      - MALLOC_ARENA_MAX=2
    volumes:
      - redis-data:/data
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  redis-data:
    driver: local